config/routes.rb
ZulsPrices::Application.routes.draw do
  resources :shoes

  resources :repairs

  devise_for :users

  resources :lists

   root :to => 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :comments, :gender, :item, :price
  validates_presence_of :gender, :item
  validates_inclusion_of :gender, :in => %w(both child gents household ladies),
                        :message => "values should be (both child gents household ladies)"
end

app/models/repair.rb
class Repair < ActiveRecord::Base
  attr_accessible :comment, :garment, :item, :price
  validates_presence_of :garment, :item
  validates_inclusion_of :garment, :in => %w(badge blouse coat curtain dress jacket jumper shirt skirt trouser),
                         :message => "values should be (badge blouse coat curtain dress jacket jumper shirt skirt trouser)"
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  attr_accessible :comment, :gender, :item, :price
  validates_presence_of :gender, :item
  validates_inclusion_of :gender, :in => %w(gents ladies),
                         :message => "values should be (gents ladies)"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  # Check that the user is logged in
  before_filter :authenticate_user!

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all( :order => :item)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  # Check that the user is logged in
  before_filter :authenticate_user!

  # GET /repairs
  # GET /repairs.json
  def index
    @repairs = Repair.all( :order => :item)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repairs }
    end
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
    @repair = Repair.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repair }
    end
  end

  # GET /repairs/new
  # GET /repairs/new.json
  def new
    @repair = Repair.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repair }
    end
  end

  # GET /repairs/1/edit
  def edit
    @repair = Repair.find(params[:id])
  end

  # POST /repairs
  # POST /repairs.json
  def create
    @repair = Repair.new(params[:repair])

    respond_to do |format|
      if @repair.save
        format.html { redirect_to @repair, notice: 'Repair was successfully created.' }
        format.json { render json: @repair, status: :created, location: @repair }
      else
        format.html { render action: "new" }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repairs/1
  # PUT /repairs/1.json
  def update
    @repair = Repair.find(params[:id])

    respond_to do |format|
      if @repair.update_attributes(params[:repair])
        format.html { redirect_to @repair, notice: 'Repair was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @repair = Repair.find(params[:id])
    @repair.destroy

    respond_to do |format|
      format.html { redirect_to repairs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

  # Check that the user is logged in
  before_filter :authenticate_user!

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all( :order => :item)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shoes }
    end
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @shoe = Shoe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shoe }
    end
  end

  # GET /shoes/new
  # GET /shoes/new.json
  def new
    @shoe = Shoe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shoe }
    end
  end

  # GET /shoes/1/edit
  def edit
    @shoe = Shoe.find(params[:id])
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(params[:shoe])

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render json: @shoe, status: :created, location: @shoe }
      else
        format.html { render action: "new" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shoes/1
  # PUT /shoes/1.json
  def update
    @shoe = Shoe.find(params[:id])

    respond_to do |format|
      if @shoe.update_attributes(params[:shoe])
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe = Shoe.find(params[:id])
    @shoe.destroy

    respond_to do |format|
      format.html { redirect_to shoes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zuls Prices</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.min.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= image_tag "DigiserveLogo5.png", :width => "65%", :style => 'display: block; margin-left: auto; margin-right: auto;' %>

<div id="user_nav" >
  <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign_out", destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<div data-role="header">
  <div data-role="navbar"  data-iconpos="top" >

    <ul>

      <li><%= link_to 'Clean',  lists_path, {"data-icon" =>"grid", "data-ajax" =>"false", "data-theme"=>"b"} %></li>

      <li><%= link_to 'Repairs',  repairs_path, {"data-icon" =>"grid", "data-ajax" =>"false", "data-theme"=>"b"} %></li>

      <li><%= link_to 'Shoes',  shoes_path, {"data-icon" =>"grid", "data-ajax" =>"false", "data-theme"=>"b"} %></li>

    </ul>

<!-- end .header --></div>

<%= yield %>

  <div data-role="footer">
    <h4>Digiserve Copyright 2013</h4>
    <!-- end .footer --></div>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div data-role="header">


<h1>Edit Item</h1>
<%= link_to 'Back', list_path, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>

  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview"  data-inset="true">



    <%= render 'form' %>


  </ul>
  <!-- end .content --></div>

app/views/lists/index.html.erb
<div data-role="header">
  <h1>Listing Cleaning Items</h1>
  <!-- end .header --></div>



<div data-role="content" data-theme="b" data-transition= "flip" >

  <ul data-role="listview" data-filter="true" data-inset="true" data-theme="e">




    <% @lists.each do |list| %>


        <li>
          <%= link_to list.item, list %>
          <span class="ui-li-count"> Minus 10%= <%=number_to_currency(list.price*0.9,:unit=>"£")%>, Base Price=<%=number_to_currency(list.price,:unit=>"£")%>, Plus 10%= <%=number_to_currency(list.price*1.1,:unit=>"£")%>, Plus 20%=  <%=number_to_currency(list.price*1.2,:unit=>"£")%> </span>
        </li>
    <% end %>
  </ul>


  <!-- end .content --></div>

<div data-role="footer">

  <div data-role="navbar" data-position="fixed" data-iconpos="top" >

    <ul>

      <li> <%= link_to 'Add Item', new_list_path, "data-icon"=>"plus", "data-theme"=>"b" %></li>


      <li><%= link_to 'List Items', lists_path, "data-ajax" =>"false", "data-icon"=>"refresh", "data-theme"=>"b" %> </li>





    </ul>


  </div>

  <!-- end .footer --></div>

app/views/lists/new.html.erb
<div data-role="header">


  <h1>New Item</h1>

  <%= link_to 'Back', lists_path, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>


  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview"  data-inset="true">


    <%= render 'form' %>

  </ul>
  <!-- end .content --></div>

app/views/lists/show.html.erb
<div data-role="header">


  <%= link_to 'Back', lists_path, {"data-icon" =>"back", "data-ajax" =>"false", "class" => "ui-btn-left", "data-theme"=>"b"} %>

  <h1> Item:<%= @list.item%> </h1>
  </br>


  <div data-role="navbar"  data-iconpos="top" >

    <ul>

      <li> <%= link_to 'Add Item', new_list_path, "data-icon"=>"plus", "data-theme"=>"b" %></li>
      <li><%= link_to 'Edit Item',  edit_list_path(@list), {"data-icon" =>"star", "data-theme"=>"b"} %></li>
      <li><%= link_to 'Delete Item ', list_path(@list), method: :delete, data: { confirm: 'Are you sure?' },"data-icon"=>"minus" , "data-theme"=>"b" %> </li>



    </ul>

    <p id="notice"><%= notice %></p>
  </div>

  <!-- end .header --></div>

<div data-role="content" data-theme="e" data-transition= "flip">
  <ul data-role="listview" data-filter="false" data-inset="true">




    <p>
      <b>Item:</b>
      <%= @list.item %>
    </p>

    <p>
      <b>Gender:</b>
      <%= @list.gender %>
    </p>

    <p>
      <b>Price:</b>
      <%= @list.price %>
    </p>

    <p>
      <b>Comments:</b>
      <%= @list.comments %>
    </p>


  </ul>
  <!-- end .content --></div>

app/views/repairs/_form.html.erb
<%= form_for(@repair) do |f| %>
  <% if @repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
      <% @repair.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :garment %><br />
    <%= f.text_field :garment %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repairs/edit.html.erb
<div data-role="header">

  <h1>Editing repair item</h1>

  <%= link_to 'Back', repair_path, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>

  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview"  data-inset="true">



    <%= render 'form' %>


  </ul>
  <!-- end .content --></div>

app/views/repairs/index.html.erb
<div data-role="header">
  <h1>Listing Repair Items</h1>
  <!-- end .header --></div>



<div data-role="content" data-theme="b" data-transition= "flip" >

  <ul data-role="listview" data-filter="true" data-inset="true" data-theme="e">




    <% @repairs.each do |list| %>


        <li>
          <%= link_to list.item, list %>
          <span class="ui-li-count"> Minus 10%= <%=number_to_currency(list.price*0.9,:unit=>"£")%>, Base Price=<%=number_to_currency(list.price,:unit=>"£")%>, Plus 10%= <%=number_to_currency(list.price*1.1,:unit=>"£")%>, Plus 20%=  <%=number_to_currency(list.price*1.2,:unit=>"£")%> </span>
        </li>

    <% end %>
  </ul>


  <!-- end .content --></div>

<div data-role="footer">

  <div data-role="navbar" data-position="fixed" data-iconpos="top" >

    <ul>

      <li> <%= link_to 'Add Item', new_repair_path, "data-icon"=>"plus", "data-theme"=>"b" %></li>


      <li><%= link_to 'List Items', repairs_path, "data-ajax" =>"false", "data-icon"=>"refresh", "data-theme"=>"b" %> </li>





    </ul>

  </div>


  <!-- end .footer --></div>

app/views/repairs/new.html.erb
<div data-role="header">

  <h1>New repair item</h1>


  <%= link_to 'Back', repairs_path, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>


  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview"  data-inset="true">


    <%= render 'form' %>

  </ul>
  <!-- end .content --></div>

app/views/repairs/show.html.erb
<div data-role="header">


  <%= link_to 'Back', repairs_path, {"data-icon" =>"back", "data-ajax" =>"false", "class" => "ui-btn-left", "data-theme"=>"b"} %>

  <h1> Item:<%= @repair.item%> </h1>
  </br>


  <div data-role="navbar"  data-iconpos="top" >

    <ul>

      <li> <%= link_to 'Add Item', new_repair_path, "data-icon"=>"plus", "data-theme"=>"b" %></li>
      <li><%= link_to 'Edit Item',  edit_repair_path(@repair), {"data-icon" =>"star", "data-theme"=>"b"} %></li>
      <li><%= link_to 'Delete Item ', repair_path(@repair), method: :delete, data: { confirm: 'Are you sure?' },"data-icon"=>"minus" , "data-theme"=>"b" %> </li>



    </ul>

    <p id="notice"><%= notice %></p>
  </div>

  <!-- end .header --></div>

<div data-role="content" data-theme="e" data-transition= "flip">
  <ul data-role="listview" data-filter="false" data-inset="true">


<p>
  <b>Item:</b>
  <%= @repair.item %>
</p>

<p>
  <b>Garment:</b>
  <%= @repair.garment %>
</p>

<p>
  <b>Price:</b>
  <%= @repair.price %>
</p>

<p>
  <b>Comment:</b>
  <%= @repair.comment %>
</p>

</ul>
<!-- end .content --></div>

app/views/shoes/_form.html.erb
<%= form_for(@shoe) do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% @shoe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<div data-role="header">


  <h1>Edit Shoe Items</h1>
  <%= link_to 'Back', shoe_path, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>

  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview"  data-inset="true">



    <%= render 'form' %>


  </ul>
  <!-- end .content --></div>

app/views/shoes/index.html.erb
<div data-role="header">
  <h1>Listing Shoes Items</h1>
  <!-- end .header --></div>



<div data-role="content" data-theme="b" data-transition= "flip" >

  <ul data-role="listview" data-filter="true" data-inset="true" data-theme="e">




    <% @shoes.each do |list| %>


        <li>
          <%= link_to list.item, list %>
          <span class="ui-li-count"> Minus 10%= <%=number_to_currency(list.price*0.9,:unit=>"£")%>, Base Price=<%=number_to_currency(list.price,:unit=>"£")%>, Plus 10%= <%=number_to_currency(list.price*1.1,:unit=>"£")%>, Plus 20%=  <%=number_to_currency(list.price*1.2,:unit=>"£")%> </span>
        </li>

    <% end %>
  </ul>


  <!-- end .content --></div>

<div data-role="footer">

  <div data-role="navbar" data-position="fixed" data-iconpos="top" >

    <ul>

      <li> <%= link_to 'Add Item', new_shoe_path, "data-icon"=>"plus", "data-theme"=>"b" %></li>


      <li><%= link_to 'List Items', shoes_path, "data-ajax" =>"false", "data-icon"=>"refresh", "data-theme"=>"b" %> </li>





    </ul>

  </div>


  <!-- end .footer --></div>

app/views/shoes/new.html.erb
<div data-role="header">


  <h1>New Shoe Item</h1>

  <%= link_to 'Back', shoes_path, {"data-icon" =>"back", "class" => "ui-btn-left", "data-theme"=>"b"} %>


  <!-- end .header --></div>

<div data-role="content" data-theme="a" data-transition= "flip">
  <ul data-role="listview"  data-inset="true">


    <%= render 'form' %>

  </ul>
  <!-- end .content --></div>

app/views/shoes/show.html.erb
<div data-role="header">


  <%= link_to 'Back', shoes_path, {"data-icon" =>"back", "data-ajax" =>"false", "class" => "ui-btn-left", "data-theme"=>"b"} %>

  <h1> Item:<%= @shoe.item%> </h1>
  </br>


  <div data-role="navbar"  data-iconpos="top" >

    <ul>

      <li> <%= link_to 'Add Item', new_shoe_path, "data-icon"=>"plus", "data-theme"=>"b" %></li>
      <li><%= link_to 'Edit Item',  edit_shoe_path(@shoe), {"data-icon" =>"star", "data-theme"=>"b"} %></li>
      <li><%= link_to 'Delete Item ', shoe_path(@shoe), method: :delete, data: { confirm: 'Are you sure?' },"data-icon"=>"minus" , "data-theme"=>"b" %> </li>



    </ul>

    <p id="notice"><%= notice %></p>
  </div>

  <!-- end .header --></div>

<div data-role="content" data-theme="e" data-transition= "flip">
  <ul data-role="listview" data-filter="false" data-inset="true">


<p>
  <b>Item:</b>
  <%= @shoe.item %>
</p>

<p>
  <b>Gender:</b>
  <%= @shoe.gender %>
</p>

<p>
  <b>Price:</b>
  <%= @shoe.price %>
</p>

<p>
  <b>Comment:</b>
  <%= @shoe.comment %>
</p>

</ul>
<!-- end .content --></div>